# Generated by Django 5.0.6 on 2024-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NMEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('PRN', models.CharField(max_length=200)),
                ('C_N0', models.CharField(max_length=200)),
                ('ConstellationType', models.CharField(max_length=200)),
                ('SVID', models.CharField(max_length=200)),
                ('Azimuth', models.CharField(max_length=200)),
                ('Elevation', models.CharField(max_length=200)),
            ],
        ),
    ]
